repos:
- repo: local
  hooks:
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pdm run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: pdm run flake8
    types: [python]
    exclude: setup.py
