name: Contributing to the Contributors

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Maanuj-Vora/List-Contributors@1.0.3
        with:
          REPO_NAME: '${{github.repository}}'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTRIBUTOR: '## Contributors'
          FILEPATH: '/README.md'
          COLUMN_PER_ROW: '4'
          IMG_WIDTH: '50'
