name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ok_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: NorMatrix
      run: cd tests/ok_code && ../../main.py

  bad_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: NorMatrix
      run: ./.github/workflows/exec_files_not_in_main_clone.sh
