name: Check

on: [push, pull_request]

jobs:
  ok_code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: NorMatrix
      run: ./main.py test/ok_code/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Tests
      run: ./exec.sh --tests-run

  epitests-ok:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest

    steps:
    - name: get repo
      uses: actions/checkout@v2

    - name: tests ok code
      run: ./exec.sh test/ok_code/

    - name: Tests
      run: ./exec.sh --tests-run

  all_with_strategy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: get repo
        uses: actions/checkout@v2

      - name: python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: OK_CODE
        run: ./main.py test/ok_code/

      - name: TESTS
        run: ./main.py --tests-run
